os: Visual Studio 2019

clone_folder: C:\imewlconverter
version: "{branch}.{build}"

before_build:
    - MSBuild "C:\imewlconverter\src\IME WL Converter WinForm.sln" -t:restore
build_script:
    - MSBuild "C:\imewlconverter\src\IME WL Converter WinForm.sln" /t:Rebuild /p:Configuration=Release

# after_build:

test_script:
   - nunit3-console "C:\imewlconverter\src\IME WL Converter Win Test\IME WL Converter Test.csproj" -result=myresults.xml;format=AppVeyor