os: Visual Studio 2019

clone_folder: C:\imewlconverter
version: "{branch}.{build}"


build_script:
    - MSBuild "C:\imewlconverter\src\IME WL Converter WinForm.sln" /t:Rebuild /p:Configuration=Release

# after_build:
#   - go run build\ci.go archive -type zip -signer WINDOWS_SIGNING_KEY -upload ""
#   - go run build\ci.go nsis -signer WINDOWS_SIGNING_KEY -upload ""

test_script:
   - MSTest "C:\imewlconverter\src\IME WL Converter Win Test\IME WL Converter Test.csproj"