os: Visual Studio 2019

clone_folder: C:\imewlconverter
version: "{branch}.{build}"
artifacts:
    - path: imewlconverter_Windows.zip
      name: WinForm

before_build:
    - MSBuild "C:\imewlconverter\src\IME WL Converter WinForm.sln" -t:restore
    - MSBuild "C:\imewlconverter\src\ImeWlConverterCmd.sln" -t:restore
build_script:
    - MSBuild "C:\imewlconverter\src\IME WL Converter WinForm.sln" /t:Rebuild /p:Configuration=Release
    - MSBuild "C:\imewlconverter\src\ImeWlConverterCmd.sln" /t:Rebuild /p:Configuration=Release

after_build:
    - 7z a imewlconverter_Windows.zip "C:\imewlconverter\src\IME WL Converter Win\bin\Release\*.exe" "C:\imewlconverter\src\IME WL Converter Win\bin\Release\ImeWlConverterCore.dll" "C:\imewlconverter\src\IME WL Converter Win\bin\Release\Readme.txt"

# before_test:
#     - nuget restore "C:\imewlconverter\src\IME WL Converter WinForm.sln"
#     - MSBuild "C:\imewlconverter\src\IME WL Converter Win Test\IME WL Converter Test.csproj" /t:Rebuild /p:Configuration=Release
test_script:
    - nunit3-console "C:\imewlconverter\src\ImeWlConverterCoreTest\bin\Release\net46\ImeWlConverterCoreTest.dll" -result=myresults.xml;format=AppVeyor